- topic_name: "/tf_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  publisher_options:
    qos:
      durability: transient_local
  subscription_options:
    qos:
      durability: transient_local
      

