- topic_name: "/tf_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  publisher_options:
    qos:
      durability: transient_local
  subscription_options:
    qos:
      durability: transient_local
      
      
- topic_name: "/gripper/state"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "ignition.msgs.Boolean"   
  
- topic_name: "/gripper/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  
- topic_name: "/gripper/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"               
